// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU0SWaXZPb0WEIgzY6LlL2XbGNjPoRfGk',
    appId: '1:642606796713:web:08a99c587d4ffd9e88beb8',
    messagingSenderId: '642606796713',
    projectId: 'cargotmate',
    authDomain: 'cargotmate.firebaseapp.com',
    storageBucket: 'cargotmate.firebasestorage.app',
    measurementId: 'G-RMYFQ54SMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJCnoU20gUNzaSTLAwi4VTzu-tvUUJJo',
    appId: '1:642606796713:android:b36e8350c5cfacdd88beb8',
    messagingSenderId: '642606796713',
    projectId: 'cargotmate',
    storageBucket: 'cargotmate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0s8kYzB8ui-TIf1ZCPobvte3eNevSCes',
    appId: '1:642606796713:ios:cfe7c0e7fed0da8c88beb8',
    messagingSenderId: '642606796713',
    projectId: 'cargotmate',
    storageBucket: 'cargotmate.firebasestorage.app',
    iosBundleId: 'com.example.cargomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0s8kYzB8ui-TIf1ZCPobvte3eNevSCes',
    appId: '1:642606796713:ios:cfe7c0e7fed0da8c88beb8',
    messagingSenderId: '642606796713',
    projectId: 'cargotmate',
    storageBucket: 'cargotmate.firebasestorage.app',
    iosBundleId: 'com.example.cargomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU0SWaXZPb0WEIgzY6LlL2XbGNjPoRfGk',
    appId: '1:642606796713:web:339c713a0bc6f05988beb8',
    messagingSenderId: '642606796713',
    projectId: 'cargotmate',
    authDomain: 'cargotmate.firebaseapp.com',
    storageBucket: 'cargotmate.firebasestorage.app',
    measurementId: 'G-31RN660N50',
  );
}
